vich_uploader:
    db_driver: orm

    mappings:
        reclamation_images:
            uri_prefix: '%app.path.reclamation_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.reclamation_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer' 
            delete_on_update: false
            delete_on_remove: true