vich_uploader:
  db_driver: orm

  mappings:
    offres_images:
      uri_prefix: "%app.path.offres_images%"
      upload_destination: "%kernel.project_dir%/public%app.path.offres_images%"
      namer: Vich\UploaderBundle\Naming\UniqidNamer # bech kol img ykoun 3andha nom unique
      delete_on_update: false
      delete_on_remove: true
     
    