vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    mappings:
        photoprofil:
            uri_prefix: "%app.path.photoprofil%"
            upload_destination: "%kernel.project_dir%/public%app.path.photoprofil%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer # bech kol img ykoun 3andha nom unique
            delete_on_remove: true
            delete_on_update: false
