#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_list:
    path: /user-list
    controller: App\Controller\UserController::userList


# app_edit_user: 
#     path: /user-edit
#     controller: App\Controller\UserController::useredit
