#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_list:
    path: /user-list
    controller: App\Controller\UserController::userList

# app_edit_user:
#     path: /edituser/{id}
#     controller: App\Controller\UserController::edituser # Replace with your actual controller name

app_list_user:
    path: /listuser
    controller: App\Controller\UserController::listuser




app_user_profile:
    path: /profile/{id}
    controller: App\Controller\UserController::profile
    
app_show_user_profile:
    path: /showprofile    
    controller: App\Controller\UserController::userProfile


app_register:
  path: /register
  controller: App\Controller\RegistrationController::register


app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout


app_login:
    path: /login
    controller: App\Controller\SecurityController::login


app_home:
    path: /home
    controller: App\Controller\HomeController::index

user_search:
    path: /listuser/search
    controller: App\Controller\UserController::search

app_filter_users:
  path: /filter-users
  controller: App\Controller\UserController::filterUsers
  methods: ['POST']


connect_google:
    path: /connect/google
    controller: App\Controller\GoogleController::connectAction

# config/routes.yaml

block_user:
    path: /block-user/{id}
    controller: App\Controller\UserController::blockUser
 
# admin_dashboard:
#     path: /admin/dashboard
#     controller: App\Controller\AdminController::dashboard


single_blog:
    path: '/blog/{id}'
    controller: 'App\Controller\BlogController::show'

# config/routes.yaml

submit_comment:
    path: '/blog/{id}/comment'
    controller: App\Controller\BlogController::submitComment
    methods: ['POST']
    
# search
speech_recognition:
    path: /speech-recognition
    controller: App\Controller\SpeechRecognitionController::index
