#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_list:
    path: /user-list
    controller: App\Controller\UserController::userList

# app_edit_user:
#     path: /edituser/{id}
#     controller: App\Controller\UserController::edituser # Replace with your actual controller name

app_list_user:
    path: /listuser
    controller: App\Controller\UserController::listuser


app_user_profile:
    path: /profile
    controller: App\Controller\UserController::profile



app_register:
  path: /register
  controller: App\Controller\RegistrationController::register


app_login:
    path: /login
    controller: App\Controller\SecurityController::login


app_home:
    path: /home
    controller: App\Controller\HomeController::index

user_search:
    path: /listuser/search
    controller: App\Controller\UserController::search

app_filter_users:
  path: /filter-users
  controller: App\Controller\UserController::filterUsers
  methods: ['POST']
  