# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.path.photoprofil: /uploads/images/photoprofil

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    Symfony\Component\Form\FormRenderer:
        arguments: ['@twig.form.renderer', '@security.csrf.token_manager']
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # sylius.form_renderer:
    #     class: Symfony\Component\Form\FormRenderer
    #     arguments: [ '@translator', '@security.csrf.token_manager', '@form.csrf_provider' ]
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # hwi_oauth.user.provider:
    #     class: HWI\Bundle\OAuthBundle\Security\Core\User\EntityUserProvider
    #     arguments:
    #         $class: App\Entity\Utilisateur
    #         $properties:
    #             'google': 'google'
    #             'app_user_provider': 'app_user_provider'


    # # Register the EmailVerifier service if it's not already defined
  

    # # add more service definitions when explicit configuration is needed
    # # please note that last definitions always *replace* previous ones
